{
    'name': 'Education: Portal',
    'version': '19.0.1.0.0',
    'summary': 'Custom student, teacher, and parent portal for the EMIS system.',
    'author': 'Innovax Solutions',
    'category': 'Education',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'mail',
        'portal',
        'hr',
        'edu_academic_structure',
        'edu_student',
        'edu_enrollment',
        'edu_academic_progression',
        'edu_classroom',
        'edu_attendance',
        'edu_exam',
        'edu_assessment',
        'edu_result',
        'edu_fees',
        'edu_pre_admission_crm',
        'edu_hr',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/portal_sidebar_data.xml',
        'data/portal_classroom_tabs_data.xml',
        'views/portal_layout.xml',
        'views/components.xml',
        'views/teacher_templates.xml',
        'views/teacher_classroom_templates.xml',
        'views/student_templates.xml',
        'views/student_classroom_templates.xml',
        'views/parent_templates.xml',
        'views/res_users_views.xml',
        'views/edu_student_views.xml',
        'views/edu_guardian_views.xml',
        'views/hr_employee_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'edu_portal/static/src/vendor/htmx.min.js',
            'edu_portal/static/src/css/portal.css',
            'edu_portal/static/src/js/portal.js',
            'edu_portal/static/src/js/entry.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
