{
    'name': 'Education: Continuous Assessment',
    'version': '19.0.1.0.0',
    'summary': 'Continuous and non-exam assessment records for the EMIS — assignments, tests, projects, class performance.',
    'author': 'Innovax Solutions',
    'category': 'Education',
    'license': 'LGPL-3',
    'depends': [
        'mail',
        'edu_academic_structure',
        'edu_academic_progression',
        'edu_enrollment',
        'edu_student',
        'edu_classroom',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/edu_assessment_category_data.xml',
        'views/edu_assessment_category_views.xml',
        'views/edu_continuous_assessment_record_views.xml',
        'views/edu_classroom_views.xml',
        'views/edu_student_views.xml',
        'views/edu_assessment_bulk_generate_wizard_views.xml',
        'views/edu_assessment_bulk_lock_wizard_views.xml',
        'report/edu_assessment_report_actions.xml',
        'report/edu_assessment_report_templates.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
