from . import edu_academic_year
from . import edu_term
from . import edu_department
from . import edu_program
from . import edu_program_term
from . import edu_batch
from . import edu_section
from . import edu_subject
from . import edu_curriculum_line
