{
    'name': 'Education: Staff Management',
    'version': '19.0.1.0.0',
    'summary': 'Teacher and staff profiles — extends hr.employee with education-specific fields and classroom integration.',
    'author': 'Innovax Solutions',
    'category': 'Education',
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'edu_academic_structure',
        'edu_classroom',
        'edu_exam',
        'edu_attendance',
        'edu_assessment',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/hr_employee_views.xml',
        'views/edu_classroom_views.xml',
        'views/edu_exam_paper_views.xml',
        'views/edu_attendance_views.xml',
        'views/edu_assessment_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
