{
    'name': 'Education: Attendance',
    'version': '19.0.1.0.0',
    'summary': 'Student attendance tracking — register, sheet, and line pattern with time-slot sessions.',
    'author': 'Innovax Solutions',
    'category': 'Education',
    'license': 'LGPL-3',
    'depends': [
        'mail',
        'edu_academic_structure',
        'edu_academic_progression',
        'edu_student',
        'edu_classroom',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/edu_attendance_register_views.xml',
        'views/edu_attendance_sheet_views.xml',
        'views/edu_attendance_defaulters_views.xml',
        'views/res_config_settings_views.xml',
        'views/edu_student_views.xml',
        'views/edu_classroom_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
