{
    'name': 'Education: Examinations',
    'version': '19.0.1.0.0',
    'summary': 'Exam sessions, papers, marksheets, and raw marks capture for the EMIS.',
    'author': 'Innovax Solutions',
    'category': 'Education',
    'license': 'LGPL-3',
    'depends': [
        'mail',
        'edu_academic_structure',
        'edu_academic_progression',
        'edu_enrollment',
        'edu_student',
        'edu_classroom',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/edu_assessment_scheme_views.xml',
        'views/edu_back_exam_policy_views.xml',
        'views/edu_exam_session_views.xml',
        'views/edu_exam_paper_views.xml',
        'views/edu_exam_marksheet_views.xml',
        'views/edu_classroom_views.xml',
        'views/edu_batch_views.xml',
        'views/edu_student_views.xml',
        'views/edu_exam_paper_generate_wizard_views.xml',
        'views/edu_exam_marksheet_generate_wizard_views.xml',
        'views/edu_back_exam_generation_wizard_views.xml',
        'report/edu_exam_report_actions.xml',
        'report/edu_exam_report_templates.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
