from . import edu_assessment_scheme
from . import edu_back_exam_policy
from . import edu_exam_session
from . import edu_exam_paper
from . import edu_exam_paper_component
from . import edu_exam_marksheet
from . import edu_exam_marksheet_component
from . import edu_classroom
from . import edu_batch
from . import edu_student
